fibreville/minotaure

LICENSE.md, README.md, connexion.php, db/database.sql, src/connexion.php, src/continue.php, src/continuevalid.php, src/ecran.php, src/index.php, src/main.php, src/new.php, src/newcomplete.php
As https://github.com/fibreville/atrpg/pull/2 can't be merge directly, I took the main of uurshin to uschin-main in order to solve the conflict ahead.
=> Merge the PR from uurshin

db/database.sql, docker/docker-compose.yml
docker-compose.yml uses connexion_example directly.
=> FIX database.sql and docker-compose.yml

src/main.php
=> Fix SQL injection

src/css/style.css, src/ecran.php
Règle une régression introduite dans la V1.0 : à la désignation d'un traitre / leader la toute première fois la désignation ne fonctionnait plus.
=> Désignation traitre / leader

README.md
J'ai explicité le README français et je l'ai traduit en anglais.
=> Corrections et traduction anglaise

src/css/style.css, src/ecran.php, src/header.php, src/logout.php, src/new.php, src/newcomplete.php
Add logout button and improve personnage creation errors
=> logout & creation errors

db/database.sql, src/ajax.php, src/connexion_example.php, src/continuevalid.php, src/css/style.css, src/ecran.php, src/header.php, src/index.php, src/js/ajax_mj.js, src/js/ajax_pj.js, src/main.php, src/new.php, src/newcomplete.php, src/variables.php
Les hébergements gratuits ont des limites de nombre de requêtes par heure, ce qui rendait l'application très vite inutilisable.
Je suis repassé sur tous les bouts de code qui généraient trop de requêtes, pour garder le strict minimum tout en maintenant le fonctionnalités ajoutées.
Que ce soit dans la V1 ou la V2, un hébergement gratuit ne pourra de toute façon pas supporter le volume de requête de plus de quelques centaines d'utilisateur. Il faudrait conseiller de ne pas dépasser la centaines et de ne pas trop utiliser le loot sur un hébergement gratuit.
La majorité des infos qui nécessitaient beaucoup de lecture mais peu d'écriture sont maintenant stockées dans des fichiers.
=> Moins de requêtes SQL + ecrasement des dernières occurences de str/mind

src/continuevalid.php, src/css/style.css, src/header.php, src/index.php, src/newcomplete.php
Une régression avait été introduite lors de l'introduction de la possibilité de se déconnecter.
On peut maintenant se reconnecter à son personnage sans problème.
=> Reconnexion de nouveau possible

src/ajax.php, src/css/style.css, src/ecran.php, src/newcomplete.php
Les sondages ne remontaient pas les bons pourcentage en cas d'utilisation de tags multiples.
Les caracs de base à la création étaient inversées.
=> Sondage fonctionnels pour multitags + caracs corrigés à la création

src/ajax.php, src/css/style.css
Une régression avait été introduite dans la version précédente : impossible de voir le sondage pour les personnages si aucun tag n'était utilisé.
=> Les sondages fonctionnent même sans tag

src/ajax.php, src/css/style.css, src/ecran.php
Le leader et le traitre ne s'affichaient pas bien dans certains cas au chargement de ecran.php (reconnexion ou nomination consécutives de l'un puis l'autre).
Le loader ajax s'affichaient mal en dark mode.
=> Le leader et le traitre se chargent correctement + bugfix dark mode

src/ecran.php, src/header.php, tests/AdminTest.php
J'ai appliqué la correction de format aux tests.
J'ai changé l'ordre des includes, j'avais inversé l'ordre lors de ma dernière modification.
=> clean tests + rework ecran.php includes order

db/database.sql
Nouvelles tables et changements de champs pour faire fonctionner le dernier code mergé.
=> Changement de structure de base de données

src/continuevalid.php
Fix d'une requête essentielle pour désactiver les Pjs.
=> Les pjs redeviennent inactifs à la connexion du MJ

README.md
Juste un peu de mise à jour suite aux changements de nom et du nouveau serveur discord.
=> CHANGE travis link and ADD discord link.

src/ecran_forms.php, src/variables.php
Des blocs de codes copiés-collés foireux se sont glissés dans la dernière PR.
=> Code fantôme

src/ajax.php, src/continuevalid.php
Fix de 2 regressions sur la connexion utilisateur.
=> Deux regressions majeures

src/admin_tools.php, src/css/style.css, src/ecran_forms.php
La requête de listing des personnages est de nouveau opérationnelle.
L'ajout de tag est de nouveau opérationnel.
La carte de personnage n'affiche plus de bordure pour la partie "tags" si le personne n'a aucun tag.
=> Liste des personnages et ajout de tag de nouveau fonctionnels

src/variables.php
=> Mécanisme de traduction pour serveur

src/locale/en/LC_MESSAGES/minotaure.po
We'll need to discuss some stuff in depth on issue #100 but that's a start.
https://github.com/fibreville/minotaure/issues/100
=> Everything is translated

src/ecran_forms.php
Trad "à qui"
Sorry I'm working with github web UI I did not find how to put all three commits in a single PR.
=> Missing GetText 2

src/locale/en/LC_MESSAGES/minotaure.po
Just to be ready when you run the PO tools.
=> Nouvelles trads
